spring.application.name=vimaadmin
server.port = 7219
# DataSource settings
spring.datasource.url=jdbc:postgresql://localhost:5432/vimaadmin
spring.datasource.username=postgres
spring.datasource.password=Welcome@321
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.securitykey = REDACTED
# 15 minutes for access token (in ms)
jwt.expiration=900000

# 7 days for refresh token (in ms)
jwt.refreshexpiration=604800000

#Swagger

auth.type=Bearer Authentication

# OAuth2 Client Configuration for Google
spring.security.oauth2.client.registration.google.client-id=REDACTED_GOOGLE_OAUTH_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=REDACTED_GOOGLE_OAUTH_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Optional: You can override Google's default provider settings
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# Optional: Redirect URI (usually handled automatically, but can be set)
# spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}



