package com.vimainsurance.vimaadmin.notification.enums;

public enum NotificationEventType {
    ENDORSEMENT_UPLOADED,
    ENROLLMENT_ALL_SUBMITTED,
    ENROLLMENT_SUBMISSION_APPROVED,
    ENDORSEMENT_COMPLETED,
    ENROLLMENT_WINDOW_OPENED,
    ENROLLMENT_WINDOW_CLOSING_SOON,
    ENROLLMENT_WINDOW_CLOSED,
    EMPLOYEE_CLAIM_SUBMITTED,
    EMPLOYEE_CLAIM_QUERY_RAISED,
    EMPLOYEE_CLAIM_QUERY_RESPONDED,
    EMPLOYEE_CLAIM_QUERY_RESPONSE_SUBMITTED,
    EMPLOYEE_CLAIM_APPROVED,
    EMPLOYEE_CLAIM_REJECTED,
    EMPLOYEE_CLAIM_SETTLED
}
