name: Test EC2 Connection

on:
  workflow_dispatch:

jobs:
  test-ec2-ssh:
      runs-on: self-hosted   # uses your EC2 runner
      steps:
        - name: Print system info
          run: |
            echo "✅ Running inside EC2"
            hostname
            whoami
            uptime
