name: Build & Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java with Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install Zoho SDK JAR locally
        run: |
            mvn install:install-file \
            -Dfile=lib/zohocrmsdk-5-0-6.0.0.jar \
            -DgroupId=com.zoho.crm \
            -DartifactId=zohocrmsdk-5-0 \
            -Dversion=6.0.0 \
            -Dpackaging=jar
            
      - name: Build jar with Maven
        run: mvn clean verify
      - name: Debug paths
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing target directory:"
          ls -lh target || echo "❌ No target folder found"
          echo "Listing home directory:"
          ls -lh ~
      - name: Move jar to deploy directory
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Jar built: $JAR_FILE"
          cp "$JAR_FILE" /home/ubuntu/vima-app-deployment/api/artifact/
          echo "✅ JAR moved to ~/vima-app-deployment/api/artifact/vimaadmin-0.0.1-SNAPSHOT.jar"

      - name: Restart Docker Compose services
        run: |
          cd ~/vima-app-deployment
          docker compose down
          docker compose up -d
          echo "✅ Docker Compose services restarted"     
